name: CI

on:
  push:
  pull_request:

jobs:
  # Run "pre-commit run --all-files"
  pre-commit:
    name: Run pre-commit hook

    runs-on: ubuntu-latest
    timeout-minutes: 2

    env:
      PYTHON_VERSION: 3.8

    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: Set up Python ${{ env.PYTHON_VERSION }}
        uses: actions/setup-python@v2
        with:
          python-version: ${{ env.PYTHON_VERSION }}

      - name: Run pre-commit
        uses: pre-commit/action@v2.0.0

      - name: Help message if pre-commit fail
        if: ${{ failure() }}
        run: |
          echo "You can install pre-commit hooks to automatically run formatting"
          echo "on each commit with:"
          echo "    pre-commit install"
          echo "or you can run by hand on staged files with"
          echo "    pre-commit run"
          echo "or after-the-fact on already committed files with"
          echo "    pre-commit run --all-files"

  build:
    name: Build

    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: Set up Python
        uses: actions/setup-python@v2
        with:
          python-version: "3.8"

      - name: Update pip
        run: |
          pip install --upgrade pip
          pip install --upgrade wheel setuptools

      - name: Get pip cache dir
        id: pip-cache
        run: |
          echo "::set-output name=dir::$(pip cache dir)"

      - name: Cache pip
        uses: actions/cache@v2
        with:
          path: |
            ${{ steps.pip-cache.outputs.dir }}
            .mypy_cache
          key: ${{ runner.os }}-python-${{ matrix.python-version }}-pip-${{ hashFiles('**/requirements*.txt') }}-git-${{ github.sha }}
          restore-keys: |
            ${{ runner.os }}-python-pip-${{ hashFiles('**/requirements*.txt') }}
            ${{ runner.os }}-python-pip-
            ${{ runner.os }}-python
            ${{ runner.os }}-

      - name: Install dependencies
        run: |
          pip install --upgrade --upgrade-strategy eager --pre -e .
          pip freeze

      - name: Run the App
        run: |
          set -eux

          python run.py &
          TASK_PID=$!
          # Make sure the task is running
          ps -p $TASK_PID || exit 1
          sleep 5
          kill $TASK_PID

      - name: Build Docker image
        uses: docker/build-push-action@ad44023a93711e3deb337508980b4b5e9bcdc5dc
        with:
          context: .
          push: false
